//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_TrackingTool.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Applied_Jobs
    {
        public int Job_id { get; set; }
        [Required]
        [DisplayName("Job Title:")]
        public string Job_Title { get; set; }
        [Required]
        [DisplayName("Vendor:")]
        public string Vendor { get; set; }
        [Required]
        [DisplayName("Client:")]
        public string Client { get; set; }
        [Required]
        [DisplayName("VendorPOC:")]
        public string VendorPOC { get; set; }
        [Required]
        [DisplayName("Submitted Rate:")]
        public string Submitted_Rate { get; set; }
        [Required]
        [DisplayName("Candidates Submitted:")]
        public string Candidates_Submitted { get; set; }
        [Required]
        [DisplayName("Status:")]
        public string Status { get; set; }
        [Required]
        [DisplayName("Additional Information:")]
        [DataType(DataType.MultilineText)]
        public string Additional_Info { get; set; }
        [Required]
        [DisplayName("Date Received:")]
        public System.DateTime Date_Recevied { get; set; }
        [Required]
        [DisplayName("Location:")]
        public string Location { get; set; }
    }
}
