//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_TrackingTool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lenoraEntities : DbContext
    {
        public lenoraEntities()
            : base("name=lenoraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detail> Details { get; set; }
        public virtual DbSet<Job_Description> Job_Description { get; set; }
        public virtual DbSet<Applied_Jobs> Applied_Jobs { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
    }
}
