//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_TrackingTool.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Detail
    {
        public int Candidate_id { get; set; }
        [Required]
        [DisplayName("First Name:")]
        public string First_Name { get; set; }
        [Required]
        [DisplayName("Last Name:")]
        public string Last_Name { get; set; }
        [Required]
        [DisplayName("Email:")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [DisplayName("Phone Number:")]
        [DataType(DataType.PhoneNumber)]
        public long Ph_Number { get; set; }
        [Required]
        [DisplayName("Visa Status:")]
        public string Visa_Status { get; set; }
        [Required]
        [DisplayName("Primary Skills:")]
        public string Primary_Skills { get; set; }
        [Required]
        [DisplayName("Secondary Skills:")]
        public string Secondary_Skills { get; set; }
        [Required]
        [DisplayName("Candidate Degree:")]
        public string Candidate_degree { get; set; }
        [Required]
        [DisplayName("Major Degree:")]
        public string Majaor_degree { get; set; }
        [Required]
        [DisplayName("Billing Status:")]
        public string Biling_Status { get; set; }
        
        [DisplayName("Resume1:")]
        [DataType(DataType.Upload)]
        public string Resume { get; set; }
        
        [DisplayName("Resume2:")]
        [DataType(DataType.Upload)]
        public byte[] Resume1 { get; set; }
    }
}
