//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_TrackingTool.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblLogin
    {
        public int user_id { get; set; }
        [Required]
        [DisplayName("User Name:")]
        public string User_name { get; set; }
        [Required]
        [DisplayName("Password:")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}
